### PR TITLE
add a screenshot for registering the mobile clients in getting starte…

### PR DESCRIPTION
**Pull request by wei-lee**
…d guide

JIRA: https://issues.jboss.org/browse/AEROGEAR-3510

Add a screenshot of the mobile client view when registering a mobile client.

ping @finp

### CODE REVIEW

**Comment by johnfriz** [comment]
@wei-lee Can you add a screenshot of how the docs look with this image in place. Will make reviewing much quicker.

**Comment by wei-lee** [comment]
screen shot 2018-07-02 at 13 14 36

**Comment by wei-lee** [comment]
@johnfriz @finp updated now. I can also move it be part of step 4 if you think it's better that way.

**Comment by johnfriz** [comment]
Looks good overall.

Not sure about the last sentence though "This screen displays a list of mobile services
that you can associate with the Mobile Client and offers to provision any mobile service that is in the service catalog but is not currently provisioned."

What does the "this" refer to at the start of the sentence - is it the project overview screen? If so, then I'm not sure the content is correct. If it's not the overview screen, then we need to clarify what "this" means.

**Comment by johnfriz** [comment]
@wei-lee - OK, looking at the source of the changes, I see that you did not write/update that sentence. However, I still think we need to change it - should it be a separate ticket or just done in this PR?

**Comment by johnfriz** [comment]
@wei-lee - It also still bothers me that the Android and iOS icons are still black & white while the Cordova and Xamarin ones are in colour. I know it's not related to this PR, but wondering if we want to fix it for community release? If so, we would need to re-do this screen shot. Thoughts?

**Comment by wei-lee** [comment]
@johnfriz I update the wording to replace "This" with "The {mobile-client} view". I think once we have the mobile client section done, we can link to it.

In terms of the icons, they are still white & black in the latest version of the web console. I don't know how much work there will be to update them, I think @jasonmadigan or @sedroche will have a better idea. I don't mind updating the screenshot again if they are updated.

But for now, I'd like to merge this PR and when we have the icons we can update it again.

**Comment by wei-lee** [comment]
I created a JIRA to capture the work to update the icons.

**Comment by johnfriz** [comment]
👍

**Pull request merged**
