### PR TITLE
update installation instructions

### PR DESCRIPTION
**Pull request by wei-lee**
## Purpose
https://issues.jboss.org/browse/AEROGEAR-9805

Type:
- [x] Technical change
- [ ] Style edit

Check that netlify build displays your changes correctly

PS.: Add images and/or .gifs to illustrate what was changed if this pull request modifies the appearance/output of something presented to the users.

### CODE REVIEW

**Comment by finp** [comment]
should we update version as part of this PR, ie here:
image

**Comment by wei-lee** [comment]
@finp yes, I have updated the value for that attribute now.

**Comment by briandooley** [comment]
@wei-lee Is there any value in keeping this going?

**Comment by briandooley** [comment]
Ping @wei-lee.

**Comment by pwright** [comment]
closing as out-of-date

**Pull request closed without merging**
