### PR TITLE
AEROGEAR - 3534 - add create user keycloak links

### PR DESCRIPTION
**Pull request by ciaranRoche**
## JIRA
https://issues.jboss.org/browse/AEROGEAR-3534
## SCREENSHOT
update-keycloak-user

### CODE REVIEW

**Comment by ciaranRoche** [comment]
I noticed that these steps are hard-coded [here](https://finp.github.io/aerogear/latest/showcase-apps.html#using-the-showcase-apps) will I update this PR to remove these steps and link to the keycloak docs too?

**Comment by johnfriz** [comment]
@ciaranRoche - Yes, please. I had spotted that too, but had not yet flagged it.

**Comment by ciaranRoche** [comment]
Showcase app keycloak steps have been updated.
keycloak-procedure

**Comment by wei-lee** [comment]
@ciaranRoche is the add `*` to Web origins still required? I remember it was causing some issues for the cordova ios showcase app? cc @StephenCoady am I right?

**Comment by ciaranRoche** [comment]
@wei-lee I am currently doing this ticket https://issues.jboss.org/browse/AEROGEAR-3526 I was going to remove it there instead.

**Comment by ciaranRoche** [comment]
@finp made those changes, if you wouldn't mind having another look

**Pull request merged**
