### PR TITLE
Review idm docs

### PR DESCRIPTION
**Pull request by cfoskin**
Ping @finp - review of the idm docs.

### CODE REVIEW

**Comment by cfoskin** [comment]
Ping @pb82

**Comment by pb82** [comment]
@cfoskin are you still adding the note about the credentials?

**Comment by cfoskin** [comment]
@pb82  I added it here: https://github.com/aerogear/mobile-docs/pull/112/files#diff-c9ccf855424bd4732865cb5a8117972bR33 is this enough?

**Comment by pb82** [comment]
@cfoskin ah right, didn't see that.

**Comment by cfoskin** [comment]
@pb82  
Can you merge? I have no permissions to do it

**Pull request merged**
