### PR TITLE
428 xamarin idm auth logout - make it not specific to showcase apps

### PR DESCRIPTION
**Pull request by pmacko1**
#428 @jhellar

### CODE REVIEW

**Comment by finp** [comment]
comparing this to android,ios,cordova, @jhellar  I think they should all be the same, right?
eg:
// User logged out successfully and local Auth tokens are deleted

**Comment by jhellar** [comment]
@finp yes, better to keep it same for all platforms

**Comment by pmacko1** [comment]
@finp @jhellar howboutnow?

**Comment by jhellar** [comment]
LGTM.

**Pull request merged**
