### PR TITLE
MOBDOC-45 change release-number to installer-release-number

### PR DESCRIPTION
**Pull request by pmacko1**
https://issues.jboss.org/browse/MOBDOC-45

### CODE REVIEW

**Comment by pb82** [comment]
@finp No worries, i can rebase my PR once you have merged this. But why are we renaming it to `installer-release-number` when it's used for other artifacts too (SDKs and APBs are also tagged with that version)?

**Comment by finp** [comment]
@pb82  can you confirm that all software will adhere to that version in future. My understanding is that release versions for these will all happen async

**Comment by pb82** [comment]
@finp According to @maleck13 this hasn't been decided yet.

**Comment by finp** [comment]
@jasonmadigan  We need to decide this issue, currently we're using {release-no} as if we're releasing a platform, not a set of services/sdks/other modules that can be versioned independently

**Comment by finp** [comment]
after discussion with @johnfriz  closing this until after community release

**Comment by jasonmadigan** [comment]
@finp grand 👍

**Pull request closed without merging**
