### PR TITLE
few typos fixed

### PR DESCRIPTION
**Pull request by pawelpaszki**
## What

A number of typos and punctuation errors fixed.

### CODE REVIEW

**Comment by pawelpaszki** [comment]
ping @finp @jstaffor

**Comment by jstaffor** [comment]
For comm release - LGTM

**Comment by finp** [comment]
@pawelpaszki  I'm going to remove ui-bundle.zip added in this PR, this should always be pulled from antora-ui repo, any objections?

**Comment by pawelpaszki** [comment]
@finp no objections.

**Pull request merged**
