### PR TITLE
Sync framework docs

### PR DESCRIPTION
**Pull request by finp**
SYNC DOCS

### CODE REVIEW

**Comment by wtrocki** [comment]
Hi Team

Knowing a large number of reviews that happened on sync docs are we in position to merge that branch into master.

ping @wei-lee @finp?

**Comment by wtrocki** [comment]
Update. Rebase needed (resolve conflicts can be used directly in github). 
We could get that merged next week.

**Comment by laurafitzgerald** [comment]
@wtrocki is there a task created in JIRA to merge the pr?

**Comment by wtrocki** [comment]
@laurafitzgerald I think that all it is now in power of the docs team that will need to put final approval and merge it.

**Pull request merged**
