### PR TITLE
[glossary] remove metrics and runtime connector from glossary

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pmacko1** [comment]
#442

**Comment by finp** [comment]
@pmacko1 why did we remove metrics?

**Comment by pmacko1** [comment]
@finp there is no glossary in metrics. Nor did metrics/ref_terminology.adoc ever exist-> antora resolved it as "include:: ..."

**Comment by finp** [comment]
@pmacko1  thanks for explanation, got it now

**Pull request merged**
