### PR TITLE
create structure for work on security service

### PR DESCRIPTION
**Pull request by finp**
## Motivation
set up file structure

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
Hi @finp did you see my pr [here](https://github.com/aerogear/mobile-docs/pull/648)?

**Comment by laurafitzgerald** [comment]
@finp I'm seeing some problems on the netlify deployment. 
screenshot 2019-03-06 at 14 50 50

**Comment by finp** [comment]
@laurafitzgerald I'd left those lines in to indicate where files should land, commented them out for now

**Comment by laurafitzgerald** [comment]
@finp could we go ahead and create the files and leave the includes there so that when we start to add the documentation it should be clear where to put it?

**Comment by finp** [comment]
@laurafitzgerald  done

**Comment by laurafitzgerald** [comment]
@finp looks like the top level `Security` nav item isn't working now. I checked it locally. Will there be a netlify build available here to also check it there? Other than that the changes look great and happy to merge it as it stands once we can verify the navigation.

**Comment by finp** [comment]
@laurafitzgerald  I changed name to match the 'new name', not sure if I 'fixed' security nav issue, could you relook?

**Comment by laurafitzgerald** [comment]
@finp still not working for me locally but it works on the netlify deployment. could be someone strange I'm doing locally.

**Pull request merged**
