### PR TITLE
AEROGEAR - 3535 - add run in emulator links

### PR DESCRIPTION
**Pull request by ciaranRoche**
## JIRA 
https://issues.jboss.org/browse/AEROGEAR-3535
## Screenshot
emulator-links

### CODE REVIEW

**Comment by ciaranRoche** [comment]
@secondsun @ziccardi @wojta Would you mind having a look at the Xamarin links I have added and check if they are ok for running a xamarin project in an emulator

**Comment by ziccardi** [comment]
@ciaranRoche : The iOS link explains only about the remote ios emulator for windows, while the android one contains screenshot from the Windows version of VisualStudio, while I've been told Windows is currently out of scope.

**Comment by laurafitzgerald** [comment]
@ciaranRoche the change looks good to me. I didn't dig into the files you've linked to as it looks like @ziccardi has already done this based on his comment.

**Comment by wei-lee** [comment]
@ciaranRoche Not sure if this is required anymore as [this file](https://github.com/aerogear/mobile-docs/blob/master/modules/ROOT/pages/_partials/build-and-deploy.adoc) is used to explain how to build and deploy the apps. Perhaps we can either merge them together, or just move this to be part of the "setup local development environment"? @johnfriz @finp thoughts?

**Comment by ciaranRoche** [comment]
@wei-lee the linked file is for running the showcase apps, is this section not for how to run a generic app in an emulator?

**Comment by wei-lee** [comment]
@ciaranRoche I think it can be used for both. Not sure where this section is being linked at the moment.

**Comment by johnfriz** [comment]
@wei-lee / @ciaranRoche - what's the status of this PR - are we updating, merging or closing?

**Comment by wei-lee** [comment]
I am happy to merge it for now. We can figure out where we need to use this content later.

**Comment by secondsun** [comment]
@wei-lee Probably shouldn't be merged if the Xamarin link is still pointing to the old Visual Studio emulator information for Xamarin

**Comment by ciaranRoche** [comment]
@secondsun @wei-lee I have updated the xamarin links

**Comment by secondsun** [comment]
LGTM!

**Pull request merged**
