### PR TITLE
AEROGEAR-3512 - add local dev link

### PR DESCRIPTION
**Pull request by ciaranRoche**
## JIRA
https://issues.jboss.org/browse/AEROGEAR-3512
## Screenshot
links

### CODE REVIEW

**Comment by johnfriz** [comment]
@ciaranRoche / @finp - The links look good - they seem to be linking to the right types of docs.

Perhaps a little more text would help set the context... Something along the lines of:

"In order to perform local development, you will need to have set up a local development environment or IDE. Mobile App development is supported across iOS Native, Android Native, Cordova and Xamarin. For information on how to set up your local development environment for these technologies, please see the links below:"

**Comment by ciaranRoche** [comment]
@finp and @johnfriz just attaching a screenshot of the blurb I added
local-setup

**Comment by johnfriz** [comment]
"Mobile services supports mobile app development across..." does not read right to me - hence the suggestion to change to "Mobile App development is supported across..."

@ciaranRoche @finp Thoughts?

**Comment by ciaranRoche** [comment]
@johnfriz I felt it best to include `Mobile Services` just to keep using our specific wording/lingo. I do agree that it does not read right, so either revert to the suggestion above or maybe we rejig it to something like 
`"Mobile Services supports mobile app development across iOS Native, Android Native, Cordova, and Xamarin. In order to perform local development, you will need to have set up a local development environment or IDE. For information on how to set up your local development environment for these technologies, please see the links below: "`
What do you think?

**Comment by johnfriz** [comment]
"Mobile Services supports mobile app development" just does not sit well with me. Even if we just changed it to "AeroGear supports mobile app development..." it would read better.

In reality, the Mobile Services themselves do not support mobile app development - the SDKs support mobile app development and communicate with the mobile services after being initialised from the mobile-services.json file.

**Comment by ciaranRoche** [comment]
@johnfriz ok cool, ill capture in a different PR and ping you in it, and we go from there.

**Pull request merged**
