### PR TITLE
AEROGEAR-3511 - Add oc cluster up pre-req

### PR DESCRIPTION
**Pull request by ciaranRoche**
## JIRA
https://issues.jboss.org/browse/AEROGEAR-3511

## Screenshot
oc-cluster1

### CODE REVIEW

**Comment by ciaranRoche** [comment]
Hey guys, I was not sure if you wanted it added as a note to the pre-req or as a bullet point. Let me know which you prefer. I'll attach a screenshot of it as a bullet point for reference
oc-cluster2

**Comment by wei-lee** [comment]
@ciaranRoche @finp I prefer the one in the first screenshot - have it in a note makes it more obvious I think. Looking at the content of the bullet points, I think maybe move it above Step 3 (Ansible). This way the step 2 & 3 are both about making sure running OpenShift locally.

**Comment by ciaranRoche** [comment]
@wei-lee and @finp updated the layout, mind having another look
updated-pre-req

**Comment by wei-lee** [comment]
+1 from me

**Pull request merged**
