### PR TITLE
update oc cluster up links

### PR DESCRIPTION
**Pull request by finp**
## Motivation
oc cluster up doc disappeared.

## What
change links to specific version md files

### CODE REVIEW

**Comment by pmacko1** [comment]
hi @finp. unfort https://github.com/openshift/origin/blob/release-3.9/docs/cluster_up_down.md#getting-started does not have a required docker version specified. There were issues with using oc 3.9 with using incompatible docker version

The docker/oc version table was present in https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md#linux 

https://github.com/openshift/origin/blob/release-3.9/docs/cluster_up_down.md#overview
is from `Jul 26, 2017`

**Comment by pmacko1** [comment]
this looks like the lost document https://github.com/openshift/origin/blob/v4.0.0-alpha.0/docs/cluster_up_down.md

**Comment by finp** [comment]
we should get the 3.9 md file updated with the info from the v4 md file

**Comment by pmacko1** [comment]
OT: https://github.com/openshift/origin/issues/21476 lol

**Comment by finp** [comment]
waiting for https://github.com/openshift/origin/pull/21588 to land before publishing

**Comment by pmacko1** [comment]
i think this is outdated @finp

**Pull request closed without merging**
