### PR TITLE
Adds mobile-clients-mobile-services_down image

### PR DESCRIPTION
**Pull request by briandooley**
@finp Review please?

### CODE REVIEW

**Comment by briandooley** [comment]
@finp Ok to proceed with this?

**Comment by finp** [comment]
@briandooley  still double imaging at https://deploy-preview-785--mobile-docs.netlify.com/aerogear/latest/mobile-developer-console/

**Comment by briandooley** [comment]
@finp Double merging is fixed now.  Can you approve this as I need it to fix other issues?

**Comment by finp** [comment]
still feel like this is the 'wrong fix', let's discuss

**Comment by briandooley** [comment]
> still feel like this is the 'wrong fix', let's discuss

Double images are still appearing.  Will review.

**Comment by briandooley** [comment]
@finp Have fixed the double image issue for this particular pr.  Can you review?  Will check for other double images later.

**Pull request merged**
