### PR TITLE
Issue#273

### PR DESCRIPTION
**Pull request by jstaffor**
https://github.com/aerogear/mobile-docs/issues/273

Needs a review as I'm not sure that the code is correct

### CODE REVIEW

**Comment by aliok** [comment]
@wtrocki can you have a look as this is IOS?

**Comment by wtrocki** [comment]
@jstaffor Is this instruction only for showcase application or generic for users.

**Comment by jstaffor** [comment]
@wtrocki tbh, I don't know. After reviewing the corresponding issue again (https://github.com/aerogear/mobile-docs/issues/273), I have come to the understanding that it applies to the the "getting starting" guide: https://docs.aerogear.org/aerogear/latest/getting-started.html#downloading-the-mobile-services-configuration-file 

The text reads:
5. Follow the next specific additional instructions depending on your platform:
 - iOS: Locate this file at the following location in your application project: <app directory>/mobile-services.json

According to Martin's comment (https://github.com/aerogear/mobile-docs/issues/273): "the directory is not the top level ios-showcase-template directory that was cloned, but is the ios-showcase-template/ios-showcase-template directory which already has an existing mobile-services.json" and so, my change hopefully addresses this. Do you think the change I made reflects this comment, and more importantly - is it right?

**Comment by wtrocki** [comment]
Basing on your comment I see that this chapter in documentation is for end user facing projects who will not have `ios-showcase-template` folder.

**Comment by finp** [comment]
closing this, seems like we need to either:
* change showcase app so that original instruction is correct
* make an exception for showcase app for location

**Comment by wtrocki** [comment]
@finp 💯 👍

**Pull request closed without merging**
