### PR TITLE
Fix Android Sync documentation

### PR DESCRIPTION
**Pull request by jhellar**

### CODE REVIEW

**Comment by pmacko1** [comment]
@jhellar do we have to squash these to 1 or Squash and Merge is enough?

**Comment by pmacko1** [comment]
@psturc is ok?

**Comment by pmacko1** [comment]
thanks guys, merging

**Comment by pmacko1** [comment]
@jhellar eh, do we have a jira for this? (consistency)

**Comment by jhellar** [comment]
@pmacko1 yes, there is this jira which should cover issues found during release testing https://issues.jboss.org/browse/AEROGEAR-7894

**Pull request merged**
